#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xrdb ${HOME}/.Xresources

xinput set-prop 13 'libinput Natural Scrolling Enabled' 1
xinput set-prop 13 "libinput Tapping Enabled" 1 

${HOME}/.fehbg

picom -f &
xsetroot -cursor_name left_ptr &
/bin/numlockx on

${HOME}/.config/polybar/launch.sh &
xbindkeys -f ${HOME}/.xbindkeysrc &
